# -*- coding: utf-8 -*-
"""Copy of VentasAdidasUS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6-QGmS8CfvLeldDLL2-TxyhTCmqof6j

### Ventas de Adidas en Estados Unidos

# <img src="https://upload.wikimedia.org/wikipedia/commons/2/24/Adidas_logo.png" width="150">
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("sagarmorework/adidas-us-sales")

print("Path to dataset files:", path)

import kagglehub
import os

# Descargar dataset de Kaggle
dataset_path = kagglehub.dataset_download("sagarmorework/adidas-us-sales")

# Verificar si la carpeta existe
print("Ruta del dataset:", dataset_path)
print("Archivos en la carpeta:", os.listdir(dataset_path))

import pandas as pd
import os

# Ruta correcta al archivo CSV
dataset_path = "/root/.cache/kagglehub/datasets/sagarmorework/adidas-us-sales/versions/1"
file_name = "Adidas US Sales.csv"

# Cargar el dataset en un DataFrame
df = pd.read_csv(os.path.join(dataset_path, file_name))

# Mostrar las primeras filas
df.head()

# Información general del dataset
df.info()

# Estadísticas descriptivas
df.describe()

# Contar valores nulos en cada columna
df.isnull().sum()

df.interpolate(inplace=True)

print(df.columns)

import matplotlib.pyplot as plt
import seaborn as sns

#Revisar la Distribución de Ventas
plt.figure(figsize=(8,5))
sns.histplot(df["total_sales"], bins=30, kde=True, color="blue")
plt.title("Distribución de Ventas (Total Sales)")
plt.xlabel("Ingresos")
plt.ylabel("Frecuencia")
plt.show()

#Ventas por Categoría de Producto
df_category = df.groupby("product")["total_sales"].sum().reset_index()

plt.figure(figsize=(10,5))
sns.barplot(x="product", y="total_sales", data=df_category, palette="viridis")
plt.xticks(rotation=45)
plt.title("Ventas por Producto")
plt.show()

#Tendencia de Ventas en el Tiempo
df["invoice_date"] = pd.to_datetime(df["invoice_date"])  # Convertir a formato de fecha
df_time = df.groupby("invoice_date")["total_sales"].sum().reset_index()

plt.figure(figsize=(12,5))
sns.lineplot(x="invoice_date", y="total_sales", data=df_time, marker="o", color="b")
plt.title("Tendencia de Ventas en el Tiempo")
plt.xticks(rotation=45)
plt.show()